{
    "success": true,
    "error": null,
    "issues": [
        {
            "title": "Ether send",
            "description": "In the function `_function_0x4229616d` a non-zero amount of Ether is sent to an address taken from storage slot 5.\nThere is a check on storage index 5. This storage slot can be written to by calling the function `_function_0x67f809e9`.\n\nThere is a check on storage index 5. This storage slot can be written to by calling the function `_function_0x67f809e9`.\nThere is a check on storage index 1. This storage slot can be written to by calling the function `fallback`.",
            "function": "_function_0x4229616d",
            "type": "Warning",
            "address": 1599,
            "debug": "<DEBUG-DATA>",
        },
        {
            "title": "Ether send",
            "description": "In the function `_function_0xb4022950` a non-zero amount of Ether is sent to an address taken from storage slot 5.\nThere is a check on storage index 5. This storage slot can be written to by calling the function `_function_0x67f809e9`.\n\nThere is a check on storage index 5. This storage slot can be written to by calling the function `_function_0x67f809e9`.\nThere is a check on storage index 1. This storage slot can be written to by calling the function `fallback`.\nThere is a check on storage index 5. This storage slot can be written to by calling the function `_function_0x67f809e9`.\nThere is a check on storage index 1. This storage slot can be written to by calling the function `fallback`.",
            "function": "_function_0xb4022950",
            "type": "Warning",
            "address": 1940,
            "debug": "<DEBUG-DATA>",
        },
        {
            "title": "Ether send",
            "description": "In the function `_function_0xb4022950` a non-zero amount of Ether is sent to an address taken from storage slot 5.\nThere is a check on storage index 5. This storage slot can be written to by calling the function `_function_0x67f809e9`.\n\nThere is a check on storage index 5. This storage slot can be written to by calling the function `_function_0x67f809e9`.\nThere is a check on storage index 1. This storage slot can be written to by calling the function `fallback`.\nThere is a check on storage index 5. This storage slot can be written to by calling the function `_function_0x67f809e9`.\nThere is a check on storage index 1. This storage slot can be written to by calling the function `fallback`.\nThere is a check on storage index 1. This storage slot can be written to by calling the function `fallback`.",
            "function": "_function_0xb4022950",
            "type": "Warning",
            "address": 2582,
            "debug": "<DEBUG-DATA>",
        },
        {
            "title": "Exception state",
            "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
            "function": "_function_0x57d4021b",
            "type": "Informational",
            "address": 1653,
            "debug": "<DEBUG-DATA>",
        },
        {
            "title": "Exception state",
            "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
            "function": "_function_0x9dbc4f9b",
            "type": "Informational",
            "address": 2085,
            "debug": "<DEBUG-DATA>",
        },
        {
            "title": "Invariant branch condition",
            "description": "Found a conditional jump which always follows the same branch",
            "function": "fallback",
            "type": "Informational",
            "address": 3111,
            "debug": "<DEBUG-DATA>",
        },
        {
            "title": "Invariant branch condition",
            "description": "Found a conditional jump which always follows the same branch",
            "function": "fallback",
            "type": "Informational",
            "address": 3140,
            "debug": "<DEBUG-DATA>",
        },
        {
            "title": "Invariant branch condition",
            "description": "Found a conditional jump which always follows the same branch",
            "function": "fallback",
            "type": "Informational",
            "address": 2950,
            "debug": "<DEBUG-DATA>",
        },
        {
            "title": "Invariant branch condition",
            "description": "Found a conditional jump which always follows the same branch",
            "function": "fallback",
            "type": "Informational",
            "address": 1268,
            "debug": "<DEBUG-DATA>",
        },
        {
            "title": "Invariant branch condition",
            "description": "Found a conditional jump which always follows the same branch",
            "function": "_function_0x09dfdc71",
            "type": "Informational",
            "address": 310,
            "debug": "<DEBUG-DATA>",
        },
        {
            "title": "Invariant branch condition",
            "description": "Found a conditional jump which always follows the same branch",
            "function": "_function_0x09dfdc71",
            "type": "Informational",
            "address": 1316,
            "debug": "<DEBUG-DATA>",
        },
        {
            "title": "Invariant branch condition",
            "description": "Found a conditional jump which always follows the same branch",
            "function": "_function_0x253459e3",
            "type": "Informational",
            "address": 1375,
            "debug": "<DEBUG-DATA>",
        },
        {
            "title": "Invariant branch condition",
            "description": "Found a conditional jump which always follows the same branch",
            "function": "_function_0x4229616d",
            "type": "Informational",
            "address": 1511,
            "debug": "<DEBUG-DATA>",
        },
        {
            "title": "Invariant branch condition",
            "description": "Found a conditional jump which always follows the same branch",
            "function": "_function_0x57d4021b",
            "type": "Informational",
            "address": 1679,
            "debug": "<DEBUG-DATA>",
        },
        {
            "title": "Invariant branch condition",
            "description": "Found a conditional jump which always follows the same branch",
            "function": "_function_0x6fbaaa1e",
            "type": "Informational",
            "address": 618,
            "debug": "<DEBUG-DATA>",
        },
        {
            "title": "Invariant branch condition",
            "description": "Found a conditional jump which always follows the same branch",
            "function": "_function_0x8a5fb3ca",
            "type": "Informational",
            "address": 805,
            "debug": "<DEBUG-DATA>",
        },
        {
            "title": "Invariant branch condition",
            "description": "Found a conditional jump which always follows the same branch",
            "function": "_function_0x9dbc4f9b",
            "type": "Informational",
            "address": 2187,
            "debug": "<DEBUG-DATA>",
        },
        {
            "title": "Unchecked CALL return value",
            "description": "The return value of an external call is not checked. Note that execution continue even if the called contract throws.",
            "function": "_function_0x4229616d",
            "type": "Informational",
            "address": 1599,
            "debug": "<DEBUG-DATA>",
        },
        {
            "title": "Unchecked CALL return value",
            "description": "The return value of an external call is not checked. Note that execution continue even if the called contract throws.",
            "function": "_function_0xb4022950",
            "type": "Informational",
            "address": 1940,
            "debug": "<DEBUG-DATA>",
        },
        {
            "title": "Unchecked CALL return value",
            "description": "The return value of an external call is not checked. Note that execution continue even if the called contract throws.",
            "function": "_function_0xb4022950",
            "type": "Informational",
            "address": 2582,
            "debug": "<DEBUG-DATA>",
        },
    ],
}
